[package]
name = "rwh-ch10-rust"
version = "0.1.0"
authors = ["Bietola <dincio.montesi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bstr = "0.2.13"
indoc = "0.3.6"
newtype = "0.2.1"
